## **Natural Language Processing Task**

# Task-1
**You need to translate each word or sentence from English to Spanish, French and German **

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
MLT = pd.read_csv("English.csv")

In [ ]:
MLT

                                  English words/sentences
0                                                     Hi.
1                                                    Run!
2                                                    Run!
3                                                    Who?
4                                                    Wow!
...                                                   ...
175616  Top-down economics never works, said Obama. "T...
175617  A carbon footprint is the amount of carbon dio...
175618  Death is something that we're often discourage...
175619  Since there are usually multiple websites on a...
175620  If someone who doesn't know your background sa...

[175621 rows x 1 columns]

In [ ]:
MLT.head()

  English words/sentences
0                     Hi.
1                    Run!
2                    Run!
3                    Who?
4                    Wow!

In [ ]:
MLT["English"] = MLT["English words/sentences"].str.replace('[?.!]',"")

<ipython-input-14-ac36a9748943>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  MLT["English"] = MLT["English words/sentences"].str.replace('[?.!]',"")

In [ ]:
MLT.head(10)

  English words/sentences English
0                     Hi.      Hi
1                    Run!     Run
2                    Run!     Run
3                    Who?     Who
4                    Wow!     Wow
5                   Fire!    Fire
6                   Help!    Help
7                   Jump.    Jump
8                   Stop!    Stop
9                   Stop!    Stop

In [ ]:
MLT=MLT.drop(columns = ["English words/sentences"])

In [ ]:
MLT.duplicated().sum()

52645

In [ ]:
MLT["English"].drop_duplicates()

0                                                        Hi
1                                                       Run
3                                                       Who
4                                                       Wow
5                                                      Fire
                                ...
175616    Top-down economics never works, said Obama "Th...
175617    A carbon footprint is the amount of carbon dio...
175618    Death is something that we're often discourage...
175619    Since there are usually multiple websites on a...
175620    If someone who doesn't know your background sa...
Name: English, Length: 122976, dtype: object

In [ ]:
def remove_duplicates(duplist):
  noduplist = []

  for element in duplist:
    if element not in noduplist:
      noduplist.append(element)
  return noduplist

print(remove_duplicates(MLT))

['English']

In [ ]:
MLT.shape

(175621, 1)

In [ ]:
MLT.head()

  English
0      Hi
1     Run
2     Run
3     Who
4     Wow

In [ ]:
MLT.shape

(175621, 1)

In [ ]:
pip install googletrans==3.1.0a0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googletrans==3.1.0a0
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
Collecting httpx==0.13.3
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 2.6 MB/s
Collecting sniffio
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting httpcore==0.9.*
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.5 MB/s
Collecting hstspreload
  Downloading hstspreload-2022.12.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 14.1 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2022.9.24)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.8/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2.10)
Collecting rfc3986<2,>=1.3
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.8/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (3.0.4)
Collecting h11<0.10,>=0.8
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.4 MB/s
Collecting h2==3.*
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 4.5 MB/s
Collecting hyperframe<6,>=5.2.0
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16368 sha256=c61586abb0b7eae969e8b9e5eb33a5257095b131913e57f6359dded0bfecc014
  Stored in directory: /root/.cache/pip/wheels/dd/59/af/8d6c96a719763990f1c548e36b17d9efdfb767f42f7ff39f53
Successfully built googletrans
Installing collected packages: hyperframe, hpack, sniffio, h2, h11, rfc3986, httpcore, hstspreload, httpx, googletrans
Successfully installed googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2022.12.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 rfc3986-1.5.0 sniffio-1.3.0

In [ ]:
from googletrans import Translator
translator = Translator()
import googletrans

In [ ]:
print(googletrans.LANGUAGES)

{'af': 'afrikaans', 'sq': 'albanian', 'am': 'amharic', 'ar': 'arabic', 'hy': 'armenian', 'az': 'azerbaijani', 'eu': 'basque', 'be': 'belarusian', 'bn': 'bengali', 'bs': 'bosnian', 'bg': 'bulgarian', 'ca': 'catalan', 'ceb': 'cebuano', 'ny': 'chichewa', 'zh-cn': 'chinese (simplified)', 'zh-tw': 'chinese (traditional)', 'co': 'corsican', 'hr': 'croatian', 'cs': 'czech', 'da': 'danish', 'nl': 'dutch', 'en': 'english', 'eo': 'esperanto', 'et': 'estonian', 'tl': 'filipino', 'fi': 'finnish', 'fr': 'french', 'fy': 'frisian', 'gl': 'galician', 'ka': 'georgian', 'de': 'german', 'el': 'greek', 'gu': 'gujarati', 'ht': 'haitian creole', 'ha': 'hausa', 'haw': 'hawaiian', 'iw': 'hebrew', 'he': 'hebrew', 'hi': 'hindi', 'hmn': 'hmong', 'hu': 'hungarian', 'is': 'icelandic', 'ig': 'igbo', 'id': 'indonesian', 'ga': 'irish', 'it': 'italian', 'ja': 'japanese', 'jw': 'javanese', 'kn': 'kannada', 'kk': 'kazakh', 'km': 'khmer', 'ko': 'korean', 'ku': 'kurdish (kurmanji)', 'ky': 'kyrgyz', 'lo': 'lao', 'la': 'latin', 'lv': 'latvian', 'lt': 'lithuanian', 'lb': 'luxembourgish', 'mk': 'macedonian', 'mg': 'malagasy', 'ms': 'malay', 'ml': 'malayalam', 'mt': 'maltese', 'mi': 'maori', 'mr': 'marathi', 'mn': 'mongolian', 'my': 'myanmar (burmese)', 'ne': 'nepali', 'no': 'norwegian', 'or': 'odia', 'ps': 'pashto', 'fa': 'persian', 'pl': 'polish', 'pt': 'portuguese', 'pa': 'punjabi', 'ro': 'romanian', 'ru': 'russian', 'sm': 'samoan', 'gd': 'scots gaelic', 'sr': 'serbian', 'st': 'sesotho', 'sn': 'shona', 'sd': 'sindhi', 'si': 'sinhala', 'sk': 'slovak', 'sl': 'slovenian', 'so': 'somali', 'es': 'spanish', 'su': 'sundanese', 'sw': 'swahili', 'sv': 'swedish', 'tg': 'tajik', 'ta': 'tamil', 'te': 'telugu', 'th': 'thai', 'tr': 'turkish', 'uk': 'ukrainian', 'ur': 'urdu', 'ug': 'uyghur', 'uz': 'uzbek', 'vi': 'vietnamese', 'cy': 'welsh', 'xh': 'xhosa', 'yi': 'yiddish', 'yo': 'yoruba', 'zu': 'zulu'}

In [ ]:
MLT_1=pd.DataFrame(MLT.iloc[0:2500,:].values, columns = ["English"])
MLT_1["Spanish"] = MLT_1['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_1["German"] = MLT_1['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_1["French"] = MLT_1['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_1.to_csv("MLT_SFG_1.csv")

In [ ]:
MLT_1.head(10)

  English    Spanish    German  French
0      Hi       Hola        Hi   Salut
1     Run     Correr    Laufen  Courir
2     Run     Correr    Laufen  Courir
3     Who      Quién       Wer     Qui
4     Wow       Guau       Wow    Ouah
5    Fire      Fuego     Feuer     Feu
6    Help      Ayuda     Hilfe   Aider
7    Jump      Salto  Springen    Saut
8    Stop  Deténgase      Halt   Arrêt
9    Stop  Deténgase      Halt   Arrêt

In [ ]:
MLT_2=pd.DataFrame(MLT.iloc[2500:5000,:].values, columns = ["English"])
MLT_2["Spanish"] = MLT_2['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_2["German"] = MLT_2['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_2["French"] = MLT_2['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_1.to_csv("MLT_SFG_2.csv")

NameError: ignored

In [ ]:
MLT_3=pd.DataFrame(MLT.iloc[5000:7500,:].values, columns = ["English"])
MLT_3["Spanish"] = MLT_3['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_3["German"] = MLT_3['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_3["French"] = MLT_3['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_3.to_csv("MLT_SFG_3.csv")

In [ ]:
MLT_4=pd.DataFrame(MLT.iloc[5000:7500,:].values, columns = ["English"])
MLT_4["Spanish"] = MLT_4['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_4["German"] = MLT_4['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_4["French"] = MLT_4['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_4.to_csv("MLT_SFG_4.csv")

In [ ]:
MLT_5=pd.DataFrame(MLT.iloc[7500:10000,:].values, columns = ["English"])
MLT_5["Spanish"] = MLT_5['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_5["German"] = MLT_5['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_5["French"] = MLT_5['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_5.to_csv("MLT_SFG_5.csv")

In [ ]:
MLT_6=pd.DataFrame(MLT.iloc[170000:175621,:].values, columns = ["English"])
MLT_6["Spanish"] = MLT_6['English'].apply(translator.translate, src='en', dest='es').apply(getattr, args=('text',))
MLT_6["German"] = MLT_6['English'].apply(translator.translate, src='en', dest='de').apply(getattr, args=('text',))
MLT_6["French"] = MLT_6['English'].apply(translator.translate, src='en', dest='fr').apply(getattr, args=('text',))

MLT_6.to_csv("MLT_SFG_6.csv")

In [ ]:
MLT_6.head()

,English,Spanish,German,French
0,The guards found a hacksaw blade in the prison...,Los guardias encontraron una hoja de sierra pa...,Die Wachen fanden in der Tasche des Gefangenen...,Les gardes ont trouvé une lame de scie à métau...
1,The guards found a hacksaw blade in the prison...,Los guardias encontraron una hoja de sierra pa...,Die Wachen fanden in der Tasche des Gefangenen...,Les gardes ont trouvé une lame de scie à métau...
2,The increase in juvenile delinquency is a seri...,El aumento de la delincuencia juvenil es un gr...,Die Zunahme der Jugendkriminalität ist ein ern...,L'augmentation de la délinquance juvénile est ...
3,The intersection where the accident happened i...,La intersección donde ocurrió el accidente est...,"Die Kreuzung, an der sich der Unfall ereignete...",L'intersection où l'accident s'est produit est...
4,The intersection where the accident happened i...,La intersección donde ocurrió el accidente est...,"Die Kreuzung, an der sich der Unfall ereignete...",L'intersection où l'accident s'est produit est...

In [ ]:
ESGF = pd.concat(map(pd.read_csv,["MLT_SFG_1.csv","MLT_SFG_2.csv", "MLT_SFG_3.csv", "MLT_SFG_4.csv", "MLT_SFG_5.csv"]))
ESGF

,Unnamed: 0,English,Spanish,German,French
0,0,Hi,Hola,Hi,Salut
1,1,Run,Correr,Laufen,Courir
2,2,Run,Correr,Laufen,Courir
3,3,Who,Quién,Wer,Qui
4,4,Wow,Guau,Wow,Ouah
...,...,...,...,...,...
2495,2495,Be very careful,Ten mucho cuidado,Sei sehr vorsichtig,Soyez très prudent
2496,2496,Be very careful,Ten mucho cuidado,Sei sehr vorsichtig,Soyez très prudent
2497,2497,Be very careful,Ten mucho cuidado,Sei sehr vorsichtig,Soyez très prudent
2498,2498,Be very careful,Ten mucho cuidado,Sei sehr vorsichtig,Soyez très prudent
2499,2499,Be very careful,Ten mucho cuidado,Sei sehr vorsichtig,Soyez très prudent

In [ ]:
ESGF.drop(["Unnamed: 0"], axis = 1, inplace = True)

In [ ]:
ESGF.head()

  English Spanish  German  French
0      Hi    Hola      Hi   Salut
1     Run  Correr  Laufen  Courir
2     Run  Correr  Laufen  Courir
3     Who   Quién     Wer     Qui
4     Wow    Guau     Wow    Ouah

In [ ]:
ESGF.to_csv("ESGF.csv")

In [ ]:
T=pd.DataFrame(MLT.iloc[0:50,:].values, columns = ["English"])
T["Tamil"] = T['English'].apply(translator.translate, src='en', dest='ta').apply(getattr, args=('text',))

In [ ]:
T

   English                 Tamil
0       Hi               வணக்கம்
1      Run                   ஓடு
2      Run                   ஓடு
3      Who                   WHO
4      Wow                   ஆஹா
5     Fire                    தீ
6     Help                  உதவி
7     Jump                  தாவி
8     Stop              நிறுத்து
9     Stop              நிறுத்து
10    Stop              நிறுத்து
11    Wait              காத்திரு
12    Wait              காத்திரு
13   Go on            தொடருங்கள்
14   Go on            தொடருங்கள்
15   Go on            தொடருங்கள்
16   Hello               வணக்கம்
17   Hello               வணக்கம்
18   I see     நான் பார்க்கிறேன்
19   I try  நான் முயற்சிக்கிறேன்
20   I won  நான் வெற்றி பெற்றேன்
21   I won  நான் வெற்றி பெற்றேன்
22   I won  நான் வெற்றி பெற்றேன்
23   Oh no                  அடடா
24  Attack             தாக்குதல்
25  Attack             தாக்குதல்
26  Cheers               சியர்ஸ்
27  Cheers               சியர்ஸ்
28  Cheers               சியர்ஸ்
29  Cheers               சியர்ஸ்
30  Get up                   எழு
31  Go now       இப்பொழுது செல்
32  Go now       இப்பொழுது செல்
33  Go now       இப்பொழுது செல்
34  Got it      அறிந்துகொண்டேன்
35  Got it      அறிந்துகொண்டேன்
36  Got it      அறிந்துகொண்டேன்
37  Got it      அறிந்துகொண்டேன்
38  Got it      அறிந்துகொண்டேன்
39  Hop in            உள்ளே குதி
40  Hop in            உள்ளே குதி
41  Hug me  என்னை அணைத்துக்கொள்
42  Hug me  என்னை அணைத்துக்கொள்
43  I fell       நான் விழுந்தேன்
44  I fell       நான் விழுந்தேன்
45  I know       எனக்கு தெரியும்
46  I left      நான் கிளம்பினேன்
47  I left      நான் கிளம்பினேன்
48  I lied  நான் பொய்யுரைத்தேன்
49  I lost         நான் தோற்றேன்